OnlineStore/Controllers/ProductDashboardController.cs
using OnlineStore.DAL;
using OnlineStore.Models;
using OnlineStore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineStore.Controllers
{
    public class ProductDashboardController : Controller
    {
        // GET: ProductDashboard
        public ActionResult Index()
        {
            var dbContext = new OnlineStoreContext();
            var productDashboardViewModelList = new List<ProductDashboardViewModel>();

            var productDashboard = (from product in dbContext.Product select product);

            foreach (var item in productDashboard)
            {
                var productItem = new ProductDashboardViewModel();
                productItem.ProductId = item.ProductId;
                productItem.Name = item.Name;
                productItem.Description = item.Description;
                productItem.ImageURL = item.ImageURL;
                productItem.ListPrice = (from product in dbContext.ProductVendor where product.ProductId == item.ProductId select product.ListPrice).FirstOrDefault();

                productDashboardViewModelList.Add(productItem);
            }
            
            return View(productDashboardViewModelList);
        }

        public int CartCheckout(string cartData)
        {
            Console.WriteLine(cartData);
            return 1;
        }
    }
}

OnlineStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        @Html.ActionLink("Online Store", "Index", "ProductDashboard", new { }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li>@Html.ActionLink("Product Dashboard", "Index", "ProductDashboard", new { }, new { @class = "nav-link" })</li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="container body-content">
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Online Store</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>